# Generated by Django 4.2.1 on 2023-05-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_slip_slip_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
