# Generated by Django 4.2.1 on 2023-05-09 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0006_remove_slip_product_slip_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slip',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.cartorder'),
        ),
    ]
