# Generated by Django 4.2 on 2023-05-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyer", "0007_alter_slip_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="seller_id",
            field=models.IntegerField(default=0),
        ),
    ]
