# Generated by Django 4.2 on 2023-05-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyer", "0008_cart_seller_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartorder",
            old_name="is_paid",
            new_name="is_check",
        ),
        migrations.RenameField(
            model_name="slip",
            old_name="is_paid",
            new_name="is_check",
        ),
        migrations.AddField(
            model_name="cart",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="Order",
        ),
    ]
