# Generated by Django 4.2 on 2023-05-10 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buyer", "0010_alter_cart_seller_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="seller_id",
            new_name="seller",
        ),
    ]
