# Generated by Django 4.2.1 on 2023-05-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='store_phone',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
