# Generated by Django 4.2.1 on 2023-05-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='store_address',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
