# Generated by Django 4.2.1 on 2023-05-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerproduct',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
